# Generated by Django 4.1 on 2022-10-12 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_create_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("experiense", models.IntegerField()),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "ordering": ["first_name", "last_name"],
            },
            bases=("users.user",),
        ),
    ]
