# Generated by Django 4.1 on 2022-10-12 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_create_teacher_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("age", models.IntegerField()),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "ordering": ["first_name", "last_name"],
            },
            bases=("users.user",),
        ),
    ]
