# Generated by Django 4.1 on 2022-10-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_create_topic_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("teacher", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.teacher")),
                ("topic", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.topic")),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "article",
            },
        ),
    ]
