# Generated by Django 4.1.1 on 2022-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing_system", "0006_create_answer_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
