# Generated by Django 4.1.1 on 2022-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing_system", "0007_change_topic_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
