# Generated by Django 4.1.1 on 2022-10-18 18:02

import EDUPlatform.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_create_student_model"),
        ("testing_system", "0008_change_article_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing_system.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "test_attempt",
                "verbose_name_plural": "test_attempts",
            },
            bases=(models.Model, EDUPlatform.mixins.DateTimeMixin),
        ),
    ]
